### PR TITLE
Resolve issue 26 mimetype from stream

### LINKED ISSUE #26: mimetype from stream
Are you interested in a pull-request with something like this?

```python
def mimetype_from_stream(stream, filename=None):
    """
    Reads in stream, attempts to identify content based
    off magic number and will return the mimetype.
    If filename is provided it will be used in the computation.
    """
    assert isinstance(stream, BytesIO)
    head, foot = _stream_details(stream)
    ext = puremagic.ext_from_filename(filename) if filename else None
    return puremagic.main._magic(head, foot, True, ext)


def _stream_details(stream):
    """ Grab the start and end of the stream"""
    assert isinstance(stream, BytesIO)
    max_head, max_foot = puremagic.main._max_lengths()
    head = stream.read(max_head)
    try:
        stream.seek(-max_foot, os.SEEK_END)
    except IOError:
        stream.seek(0)
    foot = stream.read()
    return head, foot
```

I will mimic your `from_string` function more in the pull-request. In my case I only need the mime-type, not the extension.

### PR DESCRIPTION
**Pull request by robkorv**
closes #26

### CODE REVIEW

**Comment by robkorv** [comment]
@cdgriffith is there something I must do to make the test succeed? It's failing on `No such file or directory: 'box'`.

**Comment by cdgriffith** [comment]
Looks like I left a bad carryover in the workflow https://github.com/cdgriffith/puremagic/blob/master/.github/workflows/tests.yml#L35

Needs to be changed from `box` to `puremagic`

**Comment by robkorv** [comment]
> Looks like I left a bad carryover in the workflow https://github.com/cdgriffith/puremagic/blob/master/.github/workflows/tests.yml#L35
> 
> Needs to be changed from `box` to `puremagic`

Can I do this myself or do you have a fix somewhere I should cherry-pick?

**Comment by cdgriffith** [comment]
Should be able to change it in your branch just fine `.github/workflows/tests.yaml`

**Comment by robkorv** [comment]
failing on:
```python
puremagic/main.py:284:13: T001 print found.
            print("File '{0}' does not exist!".format(fn))
            ^
puremagic/main.py:287:13: T001 print found.
            print("'{0}' : {1}".format(fn, from_file(fn, args.mime)))
            ^
puremagic/main.py:289:13: T001 print found.
            print("'{0}' : could not be Identified".format(fn))
            ^
3     T001 print found.
```

Which is not something I diffed. Is this something that must be forced? I think the general stance is that printing for cli is ok-ish.
Else this should be a in a logger and the `PureError` except msg in a `sys.exit()` so the terminal also receives an error signal.

**Comment by cdgriffith** [comment]
Yeah I think the workflow was just copped over and somehow not tested.  I will fix that separately.

**Pull request merged**
