### PR TITLE
Improve PDF file detection, fix description

### PR DESCRIPTION
**Pull request by peterekepeter**
Hi! 

There is at least one system out in the wild that produces pdf files which start with a CRLF.

I added it as an extra entry.

Though from my testing, you can have any junk in front of the file as long as at some point you encounter the `%PDF-` string so a proper fix would be to look for the sequence of bytes/characters.

Anyways, stay safe out there!

### CODE REVIEW

**Comment by NebularNerd** [comment]
Part of the v2.0 plan is to better/faster/more awesome ways to perform matching, my experimental PR #65 would help with these fringe issues.

I never looked at a PDF header, I notice it has a version in there as well, something to file away for the future for more providing more details on matches (per #69)

**Comment by peterekepeter** [comment]
My PR does not close #94 it just covers more cases without rearchitecting anything.

I opened an issue because the PDF magic sequence can be at any offset inside the file.

**Comment by NebularNerd** [comment]
My bad, I did skim the issue where I should have read it more before suggesting the close. 

PDF's are something I wanted to look at more later on as I had a project where I needed to OCR them in bulk, being able to decipher what flavor they are before carrying out work on them would help cut down unnecessary work. 

Looking at [Wikipedia: PDF](https://en.wikipedia.org/wiki/PDF) and [PDF FileTypes](https://www.adobe.com/uk/acrobat/resources/document-files/pdf-types.html), there is a lot we can look to extract detail wise i the future.

**Comment by cdgriffith** [comment]
Thank you for the addition and fix @peterekepeter !

**Pull request merged**
